//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTreeview
{
    using System;
    using System.Collections.Generic;
    
    public partial class NodeDetail
    {
        public int NodeId { get; set; }
        public string NodeName { get; set; }
        public string IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public int ParentNodeId { get; set; }
    }
}
